
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates creative "Cosmic Scramble" rule ideas for a volleyball tournament.
 *
 * - generateCosmicScrambleRules - A function that generates rule ideas.
 * - GenerateCosmicScrambleRulesInput - The input type for the generateCosmicScrambleRules function.
 * - GenerateCosmicScrambleRulesOutput - The return type for the generateCosmicScrambleRules function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCosmicScrambleRulesInputSchema = z.object({
  gameType: z
    .string()
    .describe('The type of game for which to generate rules, e.g., "King\'s Ransom".'),
});

export type GenerateCosmicScrambleRulesInput = z.infer<
  typeof GenerateCosmicScrambleRulesInputSchema
>;

const RuleSchema = z.object({
    name: z.string().describe('The catchy name of the rule.'),
    description: z.string().describe('A brief, clear description of what the rule does.'),
});

const GenerateCosmicScrambleRulesOutputSchema = z.object({
  rules: z.array(RuleSchema).describe('An array of 4 generated Cosmic Scramble rule ideas.'),
});

export type GenerateCosmicScrambleRulesOutput = z.infer<
  typeof GenerateCosmicScrambleRulesOutputSchema
>;

export async function generateCosmicScrambleRules(
  input: GenerateCosmicScrambleRulesInput
): Promise<GenerateCosmicScrambleRulesOutput> {
  return generateCosmicScrambleRulesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCosmicScrambleRulesPrompt',
  input: {schema: GenerateCosmicScrambleRulesInputSchema},
  output: {schema: GenerateCosmicScrambleRulesOutputSchema},
  prompt: `You are an expert volleyball tournament director known for creating fun and zany game rules.

  A user wants to brainstorm some creative "Cosmic Scramble" rules for their "{{gameType}}" volleyball tournament. This is a variant of King of the Court.

  The core mechanic of a Cosmic Scramble is that it forces a player trade between the winning and losing teams on the King's Court.

  Generate a list of 4 unique and silly rules for how this player trade is determined. Each rule should have a catchy name and a simple description. The rules should be suitable for a casual, co-ed beach volleyball setting. Make them fun, unpredictable, and easy to understand.

  Here are some existing examples to avoid duplicating:
  - Birthday Swap: The two players (one from each team) whose birthday is closest to today must swap teams.
  - Alphabetical Swap: The player whose first name comes last alphabetically on the losing team swaps with the player whose first name comes last alphabetically on the other team.
  - Brightest Shirt Swap: Of all the players on both teams, the two wearing the brightest color shirts must swap.
  - Sibling Swap: The player with the most siblings on the losing team swaps places with the player with the most siblings on the other team.
  
  Return the list of rules as an array of objects.`,
});

const generateCosmicScrambleRulesFlow = ai.defineFlow(
  {
    name: 'generateCosmicScrambleRulesFlow',
    inputSchema: GenerateCosmicScrambleRulesInputSchema,
    outputSchema: GenerateCosmicScrambleRulesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
