
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates creative handicaps for a Level Up volleyball tournament.
 *
 * - generateLevelUpHandicaps - A function that generates handicap ideas.
 * - GenerateLevelUpHandicapsInput - The input type for the generateLevelUpHandicaps function.
 * - GenerateLevelUpHandicapsOutput - The return type for the generateLevelUpHandicaps function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateLevelUpHandicapsInputSchema = z.object({
  gameType: z
    .string()
    .describe('The type of game for which to generate handicaps, e.g., "Level Up".'),
});

export type GenerateLevelUpHandicapsInput = z.infer<
  typeof GenerateLevelUpHandicapsInputSchema
>;

const HandicapSchema = z.object({
    level: z.number().describe('The level this handicap applies to (2-5).'),
    description: z.string().describe('A brief, clear description of what the handicap is.'),
});

const GenerateLevelUpHandicapsOutputSchema = z.object({
  handicaps: z.array(HandicapSchema).describe('An array of 4 generated handicaps for levels 2 through 5.'),
});

export type GenerateLevelUpHandicapsOutput = z.infer<
  typeof GenerateLevelUpHandicapsOutputSchema
>;

export async function generateLevelUpHandicaps(
  input: GenerateLevelUpHandicapsInput
): Promise<GenerateLevelUpHandicapsOutput> {
  return generateLevelUpHandicapsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateLevelUpHandicapsPrompt',
  input: {schema: GenerateLevelUpHandicapsInputSchema},
  output: {schema: GenerateLevelUpHandicapsOutputSchema},
  prompt: `You are an expert volleyball tournament director known for creating fun and engaging game rules.

  A user wants to brainstorm some creative handicaps for their "{{gameType}}" volleyball tournament.

  In this format, teams "level up" when they win. With each new level, they gain a new handicap that makes the game harder for them. The handicaps are NOT cumulative.

  Generate a list of 4 unique and progressively difficult handicaps for Levels 2, 3, 4, and 5. Level 1 has no handicap.
  
  The handicaps should be suitable for a casual, co-ed beach volleyball setting. Make them fun, easy to understand, and increasingly challenging.

  Here are some existing examples to get inspiration from, but do not use them directly:
  - Level 2: All players on the team must rotate positions after each side-out.
  - Level 3: The opposing team designates your strongest hitter, who must then play defense for the entire game.
  - Level 4: All serves from your team must be underhand.
  - Level 5: No player on your team is allowed to jump.

  Return the list of handicaps as an array of objects.`,
});

const generateLevelUpHandicapsFlow = ai.defineFlow(
  {
    name: 'generateLevelUpHandicapsFlow',
    inputSchema: GenerateLevelUpHandicapsInputSchema,
    outputSchema: GenerateLevelUpHandicapsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    // Ensure the levels are correctly assigned from 2 to 5
    if (output?.handicaps) {
        output.handicaps.forEach((h, index) => {
            h.level = index + 2;
        });
    }
    return output!;
  }
);
