
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates creative power-up ideas for a volleyball tournament.
 *
 * - generatePowerUps - A function that generates power-up ideas.
 * - GeneratePowerUpsInput - The input type for the generatePowerUps function.
 * - GeneratePowerUpsOutput - The return type for the generatePowerUps function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePowerUpsInputSchema = z.object({
  gameType: z
    .string()
    .describe('The type of game for which to generate power-ups, e.g., "Power-Up Round".'),
});

export type GeneratePowerUpsInput = z.infer<
  typeof GeneratePowerUpsInputSchema
>;

const PowerUpSchema = z.object({
    name: z.string().describe('The catchy name of the power-up.'),
    description: z.string().describe('A brief, clear description of what the power-up does.'),
});

const GeneratePowerUpsOutputSchema = z.object({
  powerUps: z.array(PowerUpSchema).describe('An array of 4 generated power-up ideas.'),
});

export type GeneratePowerUpsOutput = z.infer<
  typeof GeneratePowerUpsOutputSchema
>;

export async function generatePowerUps(
  input: GeneratePowerUpsInput
): Promise<GeneratePowerUpsOutput> {
  return generatePowerUpsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePowerUpsPrompt',
  input: {schema: GeneratePowerUpsInputSchema},
  output: {schema: GeneratePowerUpsOutputSchema},
  prompt: `You are an expert volleyball tournament director known for creating fun and engaging game rules.

  A user wants to brainstorm some creative power-ups for their volleyball tournament. The game format is "{{gameType}}".

  Generate a list of 4 unique and exciting power-ups. Each power-up should have a catchy name and a simple description of its effect. The power-ups should be suitable for a casual, co-ed beach volleyball setting. Make them fun and easy to understand.

  Here are some existing examples to avoid duplicating:
  - Point Boost: Start the game with a 2-point lead.
  - Serve Advantage: Get one "do-over" on a missed serve.
  - The Equalizer: The opponent's highest-skilled player must serve underhand.
  - Secret Weapon: Choose one player on your team; their points are worth double for the first 5 points.
  
  Return the list of power-ups as an array of objects.`,
});

const generatePowerUpsFlow = ai.defineFlow(
  {
    name: 'generatePowerUpsFlow',
    inputSchema: GeneratePowerUpsInputSchema,
    outputSchema: GeneratePowerUpsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
