// This is an autogenerated file from Firebase Studio.
import {initializeApp} from 'firebase/app';

// Your web app's Firebase configuration
const firebaseConfig = {
  projectId: 'saeeds-shuffle',
  appId: '1:125373944681:web:84b71ef6ec5af3e78263f8',
  storageBucket: 'saeeds-shuffle.firebasestorage.app',
  apiKey: 'AIzaSyA0j0G-AMN-GqPNFH0toSVpX9jDoHcqUXA',
  authDomain: 'saeeds-shuffle.firebaseapp.com',
  messagingSenderId: '125373944681',
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

export {app};
